version: "3.9"

services:
  backend:
    build: ./docker/backend
#    container_name: backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - ./docs:/var/www/html/docs
    ports:
      - "8080:80"

  frontend:
    build: ./docker/frontend
#    container_name: frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
